'use client';

import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';
import { FileText } from 'lucide-react';

export function TermsDialog() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="ghost" size="icon">
          <FileText className="h-5 w-5" />
          <span className="sr-only">Terms & Conditions</span>
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[625px]">
        <DialogHeader>
          <DialogTitle className="text-2xl font-headline text-white font-bold">DRISHYAA AI – Terms & Conditions</DialogTitle>
        </DialogHeader>
        <ScrollArea className="max-h-[70vh] pr-6">
          <div className="space-y-6 text-sm text-foreground/80">
            <p className='text-xs'>Effective Date: 1 JANUARY 2026</p>
            <p>
              Welcome to DRISHYAA AI. By accessing, using, or interacting with this platform, you agree to be bound by the following Terms and Conditions. If you do not agree to these terms, please discontinue the use of DRISHYAA AI immediately.
            </p>

            <div className="space-y-2">
              <h3 className="text-lg font-bold font-headline text-white">1. Purpose of the Platform</h3>
              <p>
                DRISHYAA AI is an India-based artificial intelligence platform that provides analytical, generative, and automation capabilities for individuals, developers, and enterprises. The objectives of DRISHYAA AI include:
              </p>
              <ul className="list-disc list-inside space-y-1 pl-4">
                <li>Delivering AI-powered insights, predictions, summaries, and automated workflows.</li>
                <li>Assisting users in research, productivity, analysis, and decision-support tasks.</li>
                <li>Offering AI models trained on publicly available data, synthetic training sets, and proprietary datasets.</li>
              </ul>
              <p>All outputs generated by DRISHYAA AI are intended for informational and assistive use only.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-lg font-bold font-headline text-white">2. Nature of Content & AI-Generated Output</h3>
              <p>DRISHYAA AI generates responses algorithmically. Therefore:</p>
              <ul className="list-disc list-inside space-y-1 pl-4">
                <li>Outputs may contain inaccuracies, outdated information, or incomplete interpretations.</li>
                <li>Responses should not be treated as definitive professional, legal, financial, medical, or strategic advice.</li>
                <li>Users must independently verify critical information before relying on it.</li>
                <li>DRISHYAA AI and its creators shall not be held liable for decisions made based on AI-generated outputs.</li>
              </ul>
            </div>

            <div className="space-y-2">
              <h3 className="text-lg font-bold font-headline text-white">3. Acceptable Use of the Platform</h3>
              <p>You may:</p>
              <ul className="list-disc list-inside space-y-1 pl-4">
                  <li>Use DRISHYAA AI for personal, academic, research, and enterprise productivity.</li>
                  <li>Quote or reference AI-generated content with appropriate acknowledgment.</li>
                  <li>Integrate DRISHYAA AI outputs into projects, documents, or software (non-exclusive, non-transferable).</li>
              </ul>
              <p>You may not:</p>
              <ul className="list-disc list-inside space-y-1 pl-4">
                  <li>Use DRISHYAA AI for unlawful, defamatory, discriminatory, harmful, or malicious activities.</li>
                  <li>Attempt to extract proprietary model data, source code, or internal system architecture.</li>
                  <li>Misrepresent AI-generated outputs as verified facts, official statements, or human expert opinions.</li>
                  <li>Use the platform for generating misinformation, hate speech, or cyber-abuse.</li>
                  <li>Engage in automated scraping, bulk querying, or system overload attempts.</li>
              </ul>
              <p>Violation of acceptable use may result in immediate suspension or legal action.</p>
            </div>
            
            <div className="space-y-2">
              <h3 className="text-lg font-bold font-headline text-white">4. Data Sources & Accuracy</h3>
              <p>DRISHYAA AI uses:</p>
              <ul className="list-disc list-inside space-y-1 pl-4">
                  <li>Publicly available information</li>
                  <li>Licensed or proprietary datasets</li>
                  <li>AI-generated synthetic data</li>
                  <li>User inputs (non-personal) for improving performance</li>
              </ul>
              <p>While efforts are made to maintain accuracy and reliability, DRISHYAA AI does not guarantee:</p>
              <ul className="list-disc list-inside space-y-1 pl-4">
                  <li>Completeness</li>
                  <li>Error-free information</li>
                  <li>Real-time correctness</li>
                  <li>Consistency across sessions</li>
              </ul>
              <p>AI models evolve over time; therefore responses may vary.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-lg font-bold font-headline text-white">5. Third-Party Links, APIs & Integrations</h3>
              <p>DRISHYAA AI may incorporate:</p>
              <ul className="list-disc list-inside space-y-1 pl-4">
                  <li>External APIs</li>
                  <li>Third-party datasets</li>
                  <li>Links to external websites</li>
                  <li>External model capabilities</li>
              </ul>
              <p>These are provided solely for convenience. DRISHYAA AI does not endorse, control, or guarantee external content. Users are responsible for reviewing the terms of third-party services they interact with.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-lg font-bold font-headline text-white">6. Intellectual Property</h3>
              <p>Unless otherwise stated:</p>
              <ul className="list-disc list-inside space-y-1 pl-4">
                  <li>The name DRISHYAA AI, branding, user interface, algorithms, training pipelines, and platform architecture are the intellectual property of the creators of DRISHYAA AI.</li>
                  <li>AI-generated outputs may be used by users, but DRISHYAA AI retains rights over its underlying models and infrastructure.</li>
                  <li>Third-party content, articles, datasets, and media remain the property of their respective owners.</li>
              </ul>
              <p>Unauthorized reproduction, redistribution, or resale of DRISHYAA AI’s technology or content is prohibited.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-lg font-bold font-headline text-white">7. Limitation of Liability</h3>
              <p>DRISHYAA AI, its developers, partners, and affiliates shall not be liable for:</p>
              <ul className="list-disc list-inside space-y-1 pl-4">
                  <li>Direct, indirect, incidental, or consequential damages</li>
                  <li>Loss of data, business interruption, or financial losses</li>
                  <li>Misuse of AI-generated information</li>

                  <li>System outages, latency, or platform downtime</li>
              </ul>
              <p>Use of DRISHYAA AI is strictly at your own risk.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-lg font-bold font-headline text-white">8. Privacy & Data Handling</h3>
              <p>DRISHYAA AI follows a privacy-first approach:</p>
              <ul className="list-disc list-inside space-y-1 pl-4">
                  <li>No personal, sensitive, or personally identifiable information (PII) is collected unless voluntarily provided.</li>
                  <li>User inputs may be processed for improving AI performance, but are not sold or shared with third parties.</li>
                  <li>For contact forms, support messages, or feedback submissions, information is used solely for communication and service improvement.</li>
                  <li>Detailed privacy practices are outlined in the Privacy Policy.</li>
              </ul>
            </div>

            <div className="space-y-2">
              <h3 className="text-lg font-bold font-headline text-white">9. Updates & Modifications</h3>
              <p>DRISHYAA AI may update or modify these Terms at any time. Continued use of the platform constitutes acceptance of the updated Terms. Users are encouraged to review this page periodically.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-lg font-bold font-headline text-white">10. Governing Law & Jurisdiction</h3>
              <p>These Terms shall be governed by and interpreted in accordance with the laws of India. Any dispute shall fall under the exclusive jurisdiction of courts located in Nuapada , Odisha, India.</p>
            </div>

            <div className="space-y-2">
              <h3 className="text-lg font-bold font-headline text-white">11. Contact Information</h3>
              <p>For questions, corrections, or policy-related queries:</p>
              <p>📧 aayushxidsu.11am@gmail.com</p>
            </div>

            <div className="space-y-2 border-t border-border pt-4">
              <h3 className="text-lg font-bold font-headline text-white">Imprint / Legal Notice</h3>
              <p>DRISHYAA AI<br/>A Proprietary AI Research & Development Project<br/>Operated under: Xidotic Innovations<br/>Location: Nuapada,Odisha, India<br/>Responsible Entity: Ayush Das(Founder & Developer)<br/>Contact: aayushxidsu.11am@gmail.com</p>
              <p className="text-center text-xs pt-4">All rights reserved © Xidotic 2025</p>
            </div>

          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
